services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-webserver:latest
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    networks:
      - web

networks:
  web:
    driver: bridge
