name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.3'

      - name: Build application
        run: |
          mkdir -p build
          go build -o build/webserver ./cmd/webserver/main.go

      - name: Deploy to production
        run: |
          echo "Deploying to production server..."
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no build/webserver user@your-production-server:/path/to/production/webserver
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no user@your-production-server '
            pkill -f webserver || true
            nohup /path/to/production/webserver > /dev/null 2>&1 &
          '
